spring:
  application:
    name: boa-obra-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/boar_obra
    username: postgres 
    password: password 
    driver-class-name: org.postgresql.Driver 

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true 

    security:
      jwt:
        secret: boa-obra-jwt-secret-key-2024
        expiration: 604800000 # 7 Dias

    management: 
      endpoints: 
        web: 
          exposure:
          include: health,info,metrics 
